# Use postgres/example as user/password credentials
version: '3.1'
services:

  web:
    build: .
    environment:
      PORT: 5000
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"



